# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3

    working_directory: ~/repo

    steps:
      # load in source code
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            # fallback to using the latest cache if no exact match is found
            - v1-repo-
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      # Run commands
      - run:
          name: Install Expo CLI
          command: sudo npm install -g exp

      - run:
          name: Build Android
          command: exp build:android

  bundle_dependencies:
    docker:
      - image: circleci/node:8.11.3

    working_directory: ~/repo

    steps:
      # load in source code checked out in checkout step
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            # fallback to using the latest cache if no exact match is found
            - v1-repo-
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install missing dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  checkout:
    docker:
      - image: circleci/node:8.11.3

    working_directory: ~/repo

    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  test:
    docker:
      - image: circleci/node:8.11.3

    working_directory: ~/repo

    steps:
      # load in source code
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            # fallback to using the latest cache if no exact match is found
            - v1-repo-
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      # Run commands
      - run:
          name: Run linter
          command: yarn lint

      - run:
          name: Run unit tests
          command: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - bundle_dependencies:
          requires:
            - checkout
      - test:
          requires:
            - bundle_dependencies
      - build:
          requires:
            - bundle_dependencies
