# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Expo CLI
          command: npm install -g exp

      - run:
          name: Build Android
          command: exp build:android

  test:
    docker:
      - image: circleci/node:8.11.3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install missing dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run linter
          command: yarn lint

      - run:
          name: Run unit tests
          command: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
        requires:
          - test
